baseURL: "https://profile.gurusabarish.tech"
languageCode: "en-us"
title: "Dhia Gharsallaoui"
theme: "./.."
relativeURLs: true

googleanalytics: G-2Q12XBPN53
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

 
  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/img/profile.jpg"
  name: "Dhia Gharsallaoui"
  profession: "Engineer"
  github: "https://github.com/dhia-gharsallaoui"
  linkedin: "https://www.linkedin.com/in/gharsallaoui-dhia-eddine/"
  facebook: "https://www.facebook.com/dhia.gharsallaoui/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Dhia, a passionate Data and modelling engineer.
  I like automating things, building models, exploring scalability problems, improving efficiency and performance tuning."
  descripe_l2_person:  "I’m a strong advocate for 📜 open source, ☁️ Cloud computing, 🆕 Innovation and Automation 🤖"

  skills:
    - name: Python
      percentage: 90
    - name: R
      percentage: 85
    - name: VBA
      percentage: 80
    - name: SQL
      percentage: 70
    - name: OpenAI 
      percentage: 70
    - name: ROS 
      percentage: 70
    - name: Arena Simulation 
      percentage: 70
    - name: Antares 
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "RTE"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Modeling Engineer and Data analytics"
      startdate: June 2021
      enddate: present
      featuredpoints:
        - point: Read study of interconnected energy systems configurations
        - point: Prepare intermediate configuration 
        - point: Develop script to interact with Antares software and run the simulations
        - point: Extract results data of simulations
        - point: Develop Dynamic programming algorithms to calculate water values
        - point: Read and implement economic and technical constraints
        - point: Build different plot modules
        - point: Build the scripts in R package
        - point: Develop a Web App to facilitate interaction and manipulation of the package
    - company: "BIAT"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Data Analytics"
      startdate: Jun 2020
      enddate: Aug 2020
      featuredpoints:
        - point: Analyse customer needs
        - point: Design of a Reporting tool for BIAT's tourism subsidiaries
        - point: Implement  different functionalities in order to gather the data of the hotels
        - point: Analyze the gathered data and give a complete graphical vision to the manager
        - point: Run Machine Learning models to help managers in decision making
    - company: "TELNET"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "IA Intern"
      startdate: Jan 2020
      enddate: Aug 2020
      featuredpoints:
        - point: Model a turtlebot robot in ROS oftware environment
        - point: Prepare simulation environment on GAZEBO
        - point: Implement Reinforcement Learning algorithms with OpenAi Gym
        - point: Train the model in the virtual world 
        - point: Compare different algorithms performance  
    - company: "AsteelFlash"
      role: "Intern"
      startdate: Jan 2019
      enddate: Jul 2019
      featuredpoints:
        - point: Prepare Data base template
        - point: Link the Data base the ERP of the plant
        - point: Automate Data import 
        - point: Calculate the plant's performance indicators
        - point: Provide evolution curves of the KPIs


  # Education
  disable_education: false
  education:
    - degree: "Master MODO: Modeling, Optimization, Decision, Organization"
      branch: "Computer science"
      university: "Mines ParisTech &  Université Paris-Dauphine"
      startedyear: "2020"
      graduation: "2021"
    - degree: "National Engineering Diploma"
      branch: "Industrial Engineering"
      university: "National Engineering School of Tunis -ENIT"
      startedyear: "2018"
      graduation: "2021"
    - degree: "Preparatory cycle Mathematics and Physics"
      branch: "Mathematics and Physics"
      university: "Preparatory Institute for Engineering Studies of Tunis - IPEIT"
      startedyear: "2016"
      graduation: "2018"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "safedhia@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
