baseURL: "https://dhia-gharsallaoui.github.io"
languageCode: "en-us"
title: "Dhia Gharsallaoui"
theme: "./.."
relativeURLs: true

googleanalytics: G-2Q12XBPN53
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/img/profile.jpg"
  name: "Dhia Gharsallaoui"
  profession: "Solution Architect"
  github: "https://github.com/dhia-gharsallaoui"
  linkedin: "https://www.linkedin.com/in/gharsallaoui-dhia-eddine/"
  facebook: "https://www.facebook.com/dhia.gharsallaoui/"

  # About
  disable_about: false
  descripe_l1_person: "A Solution Architect passionate about Cloud Computing. I like automating things, building pipelines, exploring scalability problems and improving efficiency and performance."
  descripe_l2_person: "I’m a strong advocate for 📜 open source, ☁️ Cloud computing, 🆕 Innovation and Automation 🤖"

  skills:
    - name: Golang
      percentage: 90
    - name: Scala
      percentage: 85
    - name: Python
      percentage: 80
    - name: Apache Spark
      percentage: 70
    - name: Apache Kafka
      percentage: 70
    - name: Apache Druid
      percentage: 70
    - name: Ansible
      percentage: 70
    - name: Kubernetes
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "RTE"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Modeling Engineer and Data analytics"
      startdate: June 2021
      enddate: present
      featuredpoints:
        - point: Read study of interconnected energy systems configurations
        - point: Prepare intermediate configuration
        - point: Develop script to interact with Antares software and run the simulations
        - point: Extract results data of simulations
        - point: Develop Dynamic programming algorithms to calculate water values
        - point: Read and implement economic and technical constraints
        - point: Build different plot modules
        - point: Build the scripts in R package
        - point: Develop a Web App to facilitate interaction and manipulation of the package
        - point: Avoid dimensionality curse using Machine Learning aproach
    - company: "BIAT"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Data Analytics"
      startdate: Jun 2020
      enddate: Aug 2020
      featuredpoints:
        - point: Analyse customer needs
        - point: Design of a Reporting tool for BIAT's tourism subsidiaries
        - point: Implement  different functionalities in order to gather the data of the hotels
        - point: Analyze the gathered data and give a complete graphical vision to the manager
        - point: Run Machine Learning models to help managers in decision making
    - company: "TELNET"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "IA Intern"
      startdate: Jan 2020
      enddate: Aug 2020
      featuredpoints:
        - point: Model a turtlebot robot in ROS oftware environment
        - point: Prepare simulation environment on GAZEBO
        - point: Implement Reinforcement Learning algorithms with OpenAi Gym
        - point: Train the model in the virtual world
        - point: Compare different algorithms performance
    - company: "AsteelFlash"
      role: "Intern"
      startdate: Jan 2019
      enddate: Jul 2019
      featuredpoints:
        - point: Prepare Data base template
        - point: Link the Data base the ERP of the plant
        - point: Automate Data import
        - point: Calculate the plant's performance indicators
        - point: Provide evolution curves of the KPIs


  # Education
  disable_education: false
  education:
    - degree: "Master MODO: Modeling, Optimization, Decision, Organization"
      branch: "Computer science"
      university: "Mines ParisTech &  Université Paris-Dauphine"
      startedyear: "2020"
      graduation: "2021"
    - degree: "National Engineering Diploma"
      branch: "Industrial Engineering"
      university: "National Engineering School of Tunis -ENIT"
      startedyear: "2018"
      graduation: "2021"
    - degree: "Preparatory cycle Mathematics and Physics"
      branch: "Mathematics and Physics"
      university: "Preparatory Institute for Engineering Studies of Tunis - IPEIT"
      startedyear: "2016"
      graduation: "2018"

  # Projects
  disable_projects: false
  projects:
    - name: "Water values for Antares"
      img: /img/calculate water values.gif
      githublink: "https://github.com/dhia-gharsallaoui/watervalues"
      description: "This package aims at generating water values for Antares.
       It allows to run specific simulations in Antares from within R, and to use the results of these simulations to compute Bellman values and water values for each stock level and each week of the year.
       All scripts are implemented in shiny web App to facilitate the use. The obtained values can be exported to Antares and used in any study "

    - name: "Image classifier"
      img: /img/cnn.gif
      githublink: "https://github.com/dhia-gharsallaoui/Classifier-image-processing"
      description: "Build a classifier model to distinguish between fields and roads.
      Use the both ML frameworks TensorFlow and Pytorch.
      Try self made CNN model and predefined VGG19 model.
      Use Date generator to improve train quality."
    - name: "Decryption of Yuka algorithm"
      img: /img/yuka.gif
      featuredlink: "https://www.kaggle.com/dhiagharsallaoui/final-yuka"
      githublink: "https://github.com/dhia-gharsallaoui/Decryption-of-Yuka-algorithm"
      description: "Construction of a database containing the composition of nutritional foods and their YUKA score. Analyze the database and identify possible models. Verify the models with machine learning approaches"
  # Achievements
  disable_achievements: false
  achievements:
    - title: Scrum certificate
      description: Scrum Fundamentals Certified (SFC™).
      img: /img/scrum.jpg
      featuredlink: "https://www.scrumstudy.com/certification/verify?type=SFC&number=838205"
    - title: "Supervised Machine Learning: Regression"
      description: "Supervised Machine Learning: Regression IBM certificate."
      img: "/img/Supervised Machine Learning: Regression.jpg"

      featuredlink: "https://www.scrumstudy.com/certification/verify?type=SFC&number=838205"
    - title: Exploratory Data Analysis for Machine Learning
      description: Exploratory Data Analysis for Machine Learning certificate from IBM.
      img: /img/EDA_IBM.jpeg
      featuredlink: "https://www.coursera.org/account/accomplishments/verify/2JLQEMJUDN9Q?utm_source=link&utm_medium=certificate&utm_content=cert_image&utm_campaign=sharing_cta&utm_product=course"


  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "safedhia@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
